### PR TITLE
Migrated projects from net3.1 to net6.0

### PR DESCRIPTION
**Pull request by v-michaelmi**
## Purpose

* Upgrading all sample projects to use `.NET 6.0` and latest NuGet packages.
## Does this introduce a breaking change?

```
[ ] Yes
[X] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[X] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Run samples. They should work as before.

## What to Check
Verify that the following are valid
* Functionality is still the same, samples work as before.

## Other Information

There's `Microsoft.Identity.Web.Future` project in sample 4 which looks like a precursor for some of the new features like in memory caching. Leaving this in this pull request but I can also remove this.

### CODE REVIEW

**Review by jmprieur — COMMENTED** [review]
.NET 6.0 is the LTS (Long term support)
don't we want to move directly to .NET 6.0 ?

(just update the framework and references: I'm not proposing to change any code)

**Comment by aremo-ms** [comment]
> .NET 6.0 is the LTS (Long term support) don't we want to move directly to .NET 6.0 ?
> 
> (just update the framework and references: I'm not proposing to change any code)

@jmprieur @v-michaelmi  - FYI I've updated all 4 samples to .NET 6.0 including all underlying nuget packages
The DevOps pipeline was updated as well to use .NET 6.0

**Comment by aremo-ms** [comment]
@v-michaelmi we should finish this PR

**Comment by v-michaelmi** [comment]
Needed to add code enabling `.WithExperimentalFeatures()` for sample four with the certificate (it was breaking).

Everything looks good except for sample 3. I think the PowerShell script generates a bad `KeyVaultCertificateName`.

image

I'll try and patch this up. After I get that working I'll merge this through.

**Comment by v-michaelmi** [comment]
I'm thinking that we should leave the issue with sample 3 alone for now.

It's going to need some updates to the PowerShell script that are pretty far outside of the scope here.

**Comment by aremo-ms** [comment]
> I'm thinking that we should leave the issue with sample 3 alone for now.
> 
> It's going to need some updates to the PowerShell script that are pretty far outside of the scope here.

We cannot leave known issue exposed to customers. Can you think about a PowerShell script to resolve it? Once you have it, we might be able to update our automation easily. Let me know if you would like to discuss

**Comment by v-michaelmi** [comment]
@aremo-ms 

Agreed.

We should discuss this but the fix would be better served to be checked in with another branch.

**Comment by aremo-ms** [comment]
please remove Visual Studio year [here](https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/tree/update-to-net5.0#readme)

**Pull request merged**
