### PR TITLE
Trwalke/msal450

### PR DESCRIPTION
**Pull request by trwalke**
Updating to MSAL 4.5.0.

After using the app configuration scripts for both solutions, I encountered the following results:

[the first project resulted in](https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/tree/master/1-Call-MSGraph)  

image

[the second project resulted in](https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/tree/master/2-Call-OwnApi)  

image

Both tests resulted in an access token but with errors. @jmprieur are these errors expected?

### CODE REVIEW

**Comment by trwalke** [comment]
@jmprieur is it possible to make the app creation script grant admin consent for the app? I needed to do it before I was able to acquire the token.

**Comment by bgavrilMS** [comment]
I had a look at this. It seems that it takes a few minutes for AAD changes to propagate. I was able to run sample 1 and 2 with msal 4.5.0

**Comment by jmprieur** [comment]
@trwalke : when you use the scripts they tell you exactly what to do:

`
------------------------------------------------------------------------------------------------
IMPORTANT: Please follow the instructions below to complete a few manual step(s) in the Azure portal :
- For 'client'
  - Navigate to 'https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/CallAnAPI/appId/{clientId}/objectId/{objectId}/isMSAApp/'
  - Navigate to the API permissions page and click on 'Grant admin consent for {tenant}'
------------------------------------------------------------------------------------------------
`

**Comment by trwalke** [comment]
> @trwalke : when you use the scripts they tell you exactly what to do:
> 
> ## `
> IMPORTANT: Please follow the instructions below to complete a few manual step(s) in the Azure portal :
> 
> * For 'client'
>   
>   * Navigate to '[https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/CallAnAPI/appId/{clientId}/objectId/{objectId}/isMSAApp/](https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/CallAnAPI/appId/%7BclientId%7D/objectId/%7BobjectId%7D/isMSAApp/)'
>   * Navigate to the API permissions page and click on 'Grant admin consent for {tenant}'
> 
> `

oh I see. What I did was run the script directly from the explorer and when you do that powershell closes immediately so I didnt see the message.

Thanks

**Pull request merged**
