### PR TITLE
Removed Json.Net dependency, simplified code

### PR DESCRIPTION
**Pull request by tymtam2**
## Purpose

Changes only in `daemon-console`
* Simplified code 
* Removed Json.Net and used System.Text.Json instead
* Added token expiration time to output

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[x] Other... Please describe:
    Removed Json.Net dependency
    Added more output (token expiry time)
```

## How to Test
*  Get the code
*  Run the sample.

Output of developer-level testing
```
Token acquired, expires: 13/08/2020 05:50:47 +00:00 (in 00:59:58.5433870)

[
  {
    "id": 1,
    "task": "Pick up groceries"
  },
  {
    "id": 2,
    "task": "Finish invoice report"
  },
  {
    "id": 3,
    "task": "Water plants"
  }
]
Press any key to exit
```

### CODE REVIEW

**Comment by jmprieur** [comment]
Thanks @tymtam2 

I'm curious why you wanted to have all the code in the same file. (btw this is the same code in all the desktop samples, so we'd loose in consistency here)

**Comment by tymtam2** [comment]
I didn't think the helper class added any value and switching between files when learning adds - however small - mental burden. Please note that when making the call you have to jump twice (Program->CallApi->Display) 

I understand the point of reuse, however:
  * it's only few lines;
  * the namespace would be different for the desktop so it's not an identical file
  * I thought that few elements of the helper were not the best: 
     * Having `Console.WriteLine`s in `CallX` and then call `Display` seems inconsistent and unnecessary: I would argue that either `CallX` takes a log `Action` or it does the displaying itself.
     * Helper class deserialising the JObject appears half baked. I think it would be more correct to:
         * either make the method generic and deserialise to T (which would remove Program's dependency on a seraliser) 
         * or to just read the string and pass it to `Display`.
     * ```if (!string.IsNullOrEmpty(accessToken))``` and returning with feedback (console or return value) seems incorrect
     

Cheers!

**Comment by tymtam2** [comment]
Do you prefer if I leave the helper alone and submit a PR for just the serialiser and token's expiration time in the output?

**Comment by jmprieur** [comment]
@tymtam2 : yes, if you don't mind, I would prefer it better.
Do you think having all in one file is better?

**Pull request closed without merging**
